#!/usr/bin/env python
import json
import urllib2
import os
import sys


server = "http://pamrel.lu"

en_help_str = "{0} [--theme=theme] [--numbers=on/off] <file>".format(sys.argv[0])

if __name__ == "__main__":
    if len(sys.argv) <= 1 or "-h" in sys.argv or "--help" in sys.argv:
        print(en_help_str)
        sys.exit()

    paste = sys.argv[-1]

    if paste.find(".") != -1:
        file_type = paste.split(".")[-1]
    else:
        file_type = None

    theme = None
    numbers = False
    for arg in sys.argv:
        if arg.startswith("--theme="):
            theme = arg.split("=", 1)[1]
        if arg.startswith("--numbers="):
            numbers = arg.split("=", 1)[1]
            if numbers not in ["on", "off"]:
                print "Unknown --numbers={0}".format(numbers)
            numbers = True if numbers == "on" else False

    context = {
        "verb": "post",
        "object": {
            "content": open(paste).read(),
            "fileExtension": file_type,
            "theme": theme,
            "numbers": numbers,
        }
    }

    pamreltu = urllib2.build_opener(urllib2.HTTPHandler)
    request = urllib2.Request(server, data=json.dumps(context))
    request.add_header("Content-Type", "application/json")
    request.get_method = lambda: "POST"
    paste = json.loads(pamreltu.open(request).read())

    if "error" in paste:
        print("[Error] {0}".format(paste["error"]))

    url = "{server}/{pid}".format(server=server, pid=paste["object"]["id"])

    if "-o" in sys.argv:
        # open in browser
        import webbrowser
        webbrowser.open(url)
        sys.exit()

    print(url)
