#!/usr/bin/env python
import json
import urllib2
import os
import sys

from optparse import OptionParser
from datetime import datetime

# Change at will
SERVER = "http://pamrel.lu"
STORE = "~/.pamrel"

class Paste(object):
    """ Represents a Paste object """

    id = None
    filename = None
    theme = None
    created = None
    modified = None
    numbers = False
    token = None
    deleteOnDate = None
    deleteOnView = None
    
    def __init__(self, filename, **kwargs):
        self.filename = filename
        for arg, value in kwargs.items():
            setattr(self, arg, value)

    def __repr__(self):
        if self.id is not None:
            return "{filename} => {server}/{id}".format(
                filename=self.filename,
                server=SERVER,
                id=self.id)
        return self.filename

    def __str__(self):
        return str(repr(self))

    @property
    def objectType(self):
        return "paste"

    @property
    def fileType(self):
        return self.filename.split(".")[-1]

    @property
    def fileName(self):
        return self.filename.split("/")[-1]

    def post(self):
        """ Sends post to server """
        context = {
            "content": open(self.filename, "r").read(),
            "fileName": self.fileName,
            "fileExtension": self.fileType,
            "numbers": self.numbers
        }

        if self.theme is not None:
            paste["theme"] = theme

        # Paste to the server
        pamreltu = urllib2.build_opener(urllib2.HTTPHandler)
        request = urllib2.Request(SERVER, data=json.dumps(context))
        request.add_header("Content-Type", "application/json")
        request.get_method = lambda: "POST"
        self.unserialize(pamreltu.open(request).read())

    def unserialize(self, data):
        """ Loads data onto paste """
        if isinstance(data, basestring):
            data = json.loads(data)
        self.id = data["object"]["id"]
        self.theme = data["object"]["theme"]
        self.created = data["object"]["created"]
        self.modified = data["object"]["modified"]
        self.token = data["object"]["token"]

    def serialize(self):
        paste = {
            "created": self.created,
            "token": self.token,
            "modified": self.modified,
            "theme": self.theme,
            "deleteOnViews": self.deleteOnView,
            "deleteOnDate": self.deleteOnDate,
        }
        return paste

if __name__ == "__main__":
    # Make parser for CLI arguments
    parser = OptionParser()
    
    parser.add_option("-n", "--numbers",
                      default=False,
                      action="store_true",
                      dest="numbers",
                      help="Add line numbers to the paste(s)")

    parser.add_option("-d", "--delete",
                      default=False,
                      action="store_true",
                      dest="delete",
                      help="Deletes the paste(s) specified as URLs")

    parser.add_option("-s", "--syntax",
                      default=False,
                      action="store_true",
                      dest="syntax",
                      help="Enables syntax highlighting on the paste(s)")

    parser.add_option("--server",
                      dest="server",
                      help="The server you want to send the paste(s) to")

    parser.add_option("--theme",
                      dest="theme",
                      help="The theme used to display the paste(s)")

    parser.add_option("--delete-on-date",
                      dest="deleteOnDate",
                      help="Delete the paste(s) on the date specified")
    
    parser.add_option("--delete-on-views",
                      dest="deleteOnView",
                      help="Delete the paste(s) on the number of views specified")

    (options, args) = parser.parse_args()

    if not args:
        sys.stderr.write("No paste specified, use -h or --help to get usage\n")
        sys.exit()

    options = dict([(o, getattr(options, o)) for o in dir(options)
                     if not o.startswith("_")])

    for i, arg in enumerate(args):
        paste = Paste(filename=arg, **options)
        paste.post()
        print paste
        args[i] = paste

    # Store the pastes on FS
    try:
        store = os.path.expanduser(STORE)
        if os.path.exists(store):
            fp = open(store, "r+")
            data = json.loads(fp.read())
        else:
            fp = open(store, "w")
            data = {}
        fp.seek(0)
        for paste in args:
            data[paste.id] = paste.serialize()
        fp.write(json.dumps(data, indent=4, separators=(',', ': ')))
        fp.close()
    except (IOError, ValueError):
        raise
        print "[Error] Could not save paste information to {0}".format(STORE)
        print "        below are the delete tokens which can be"
        print "        used to alter or delete the paste"
        print
        for paste in args:
            print "{0} => {1}".format(paste.filename, paste.token)
 
